image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  CARGO_HOME: .cargo

services:
- docker:dind

before_script:
  - apk update
  - apk add make tar

rust-tests:
  script:
  - make test-ci
  cache:
    paths:
      - pISO/target/
      - pISO/.cargo/

make-image:
  script:
  - chmod +x buildroot/utils/should-rebuild
  - make sdimage-ci &> build.log
  artifacts:
    name: "sdimage-$CI_COMMIT_SHA"
    paths:
    - sdcard.img.tar.gz
    - build.log
    when: always
  cache:
    paths:
      - buildroot/output/
