image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  CARGO_HOME: .cargo

services:
- docker:dind

before_script:
  - apk update
  - apk add make

rust-tests:
  script:
  - make test-ci
  cache:
    paths:
      - pISO/target/
      - pISO/.cargo/

make-image:
  script:
  - make sdimage-ci &> build.log
  artifacts:
    name: "sdimage-$CI_COMMIT_REF_NAME"
    paths:
    - buildroot/output/images/sdcard.img
    - build.log
    when: always
